# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://cybersecuritychallenge.lu
title: LËTZ CYBERSECURITY CHALLENGE
email: info@securitymadein.lu
author: pst
description: > # "Write an awesome description for your new site here. 
  You are a student or a professional and passionate by hacking? Don't miss this adventure!
  The Luxembourg Cybersecurity Challenge is organized by C3, the Cybersecurity Competence Center Luxembourg.
  This competition targets open-minded creative digital natives. Our aim is not only to find talents but encourage young people to pursue a career in cybersecurity and related disciplines.
copyright: 'Copyright &copy; 2020 [SECURITYMADEIN.LU](https://securitymadein.lu/)'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: envelope
    url: mailto:info@securitymadein.lu
  - title: twitter
    url: https://twitter.com/@LetzChallenge
  - title: github
    url: https://github.com/CSCLuxembourg
  - title: linkedin
    url: https://www.linkedin.com/showcase/cscluxembourg/
